// account
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// restaurant
export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEM = 'ADD_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const GET_RESTAURANT_ORDERS = 'GET_RESTAURANT_ORDERS'
export const ADD_RESTAURANT_ORDER = 'ADD_RESTAURANT_ORDER'

// customer
export const GET_RESTAURANTS = 'GET_RESTAURANTS'
export const GET_RESTAURANT_ITEMS = 'GET_RESTAURANT_ITEMS'
export const GET_CUSTOMER_ORDERS = 'GET_CUSTOMER_ORDERS'
export const ADD_CUSTOMER_ORDER = 'ADD_CUSTOMER_ORDER'
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART'
export const EMPTY_CART = 'EMPTY_CART'

// driver
export const GET_UNTAKEN_DRIVER_ORDERS = 'GET_UNTAKEN_DRIVER_ORDERS'
export const GET_DRIVER_ORDERS = 'GET_DRIVER_ORDERS'
export const ADD_DRIVER_ORDER = 'ADD_DRIVER_ORDER'
